#!/usr/bin/env bash
# Bootstraps the lab from a fresh `make up`:
#   1. apply mongo/shards-init.js to mongos-1 (idempotent)
#   2. register the Debezium connector
#   3. seed 100 products + 100 users into Postgres so CDC produces a
#      non-empty derived store
#   4. wait for ES products index to have docs > 0
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/_lib.sh"

log_step "1) Applying mongo shard topology via mongos-1"
docker compose exec -T mongos-1 mongosh --quiet < "${LAB_ROOT}/mongo/shards-init.js"

log_step "2) Registering Debezium connector"
LAB_DEBEZIUM_PORT="${LAB_DEBEZIUM_PORT:-18083}" \
DEBEZIUM_HOST=localhost DEBEZIUM_PORT="${LAB_DEBEZIUM_PORT:-18083}" \
  bash "${LAB_ROOT}/debezium/register.sh"

log_step "3) Seeding 100 users + 100 products into Postgres"
docker compose exec -T postgres psql -U hlsa -d hlsa -v ON_ERROR_STOP=1 <<'SQL'
TRUNCATE products, users, orders RESTART IDENTITY;

INSERT INTO users (tenant_id, email, display_name)
SELECT
  'tenant-' || ((g % 50) + 1),
  'user' || g || '@example.com',
  'User ' || g
FROM generate_series(1, 100) g;

INSERT INTO products (tenant_id, sku, title, description, price_cents, stock, search_facets)
SELECT
  'tenant-' || ((g % 50) + 1),
  'sku-' || lpad(g::text, 4, '0'),
  'Product ' || g,
  'Generated by seed.sh',
  (1000 + (g * 17) % 9000),
  (50 + (g % 50)),
  ARRAY['cat-' || ((g % 5) + 1), 'tier-' || ((g % 3) + 1)]
FROM generate_series(1, 100) g;
SQL

log_step "4) Waiting for ES products index to be ready"
ES_PORT="${LAB_ELASTICSEARCH_PORT:-19200}"
for i in $(seq 1 60); do
  count=$(curl -fsS "http://localhost:${ES_PORT}/products/_count" 2>/dev/null | jq -r '.count // 0')
  if [[ -n "${count}" && "${count}" -gt 0 ]]; then
    echo "[lab43] elasticsearch products._count=${count}"
    break
  fi
  echo "[lab43] still waiting for products index... (attempt ${i})"
  sleep 2
done

if [[ "${count:-0}" -eq 0 ]]; then
  echo "[lab43] WARNING: products index did not populate within timeout"
  echo "[lab43] Inspect with: bash scripts/debezium-status.sh"
  exit 1
fi

log_step "seed complete"
